name: Build and Push Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u andreasrg --password-stdin

    - name: Build image
      run: docker build -f app/Dockerfile -t ghcr.io/andreasrg/awesome-recipe-book--2026-andreasrg-edition:latest .

    - name: Push image
      run: docker push ghcr.io/andreasrg/awesome-recipe-book--2026-andreasrg-edition:latest


