name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      run: ruff check .

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set image name
      run: echo "IMAGE_NAME=ghcr.io/andreasrg/awesome-recipe-book--2026-andreasrg-edition:latest" >> $GITHUB_ENV

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u andreasrg --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image (only on main)
      if: github.ref == 'refs/heads/main'
      run: docker push $IMAGE_NAME
